# -*- coding: utf-8 -*-
"""Profiles

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16EBRukXC65lnMWoZqClUGts_Ce9qcAjV
"""

#  Minimum Variance Profiles

# ============== Conservador ==============
volatility_percentile = 0.55      # solo el tercio menos volátil del universo
correlation_percentile = 0.60     # prioriza activos poco correlacionados con SPY (diversificación real)
max_assets_in_portfolio = 15      # más nombres, menor concentración por activo
max_weight_per_asset = 0.12       # techo bajo, evita concentración
min_weight_per_asset = 0.001

use_etf_constraint = True
etf_min_weight = 0.30             # base sólida en ETFs diversificados
etf_max_weight = 0.55

use_delta_filter = True
delta_min = 0.55                  # exige mayor probabilidad de éxito direccional

use_iv_shrinkage = True
shrinkage_min = 0.35
shrinkage_max = 0.85              # pesa fuerte hacia vol histórica (más estable)
ratio_band = 0.30

n_top_international = 5           # menor exposición a mercados menos líquidos
n_pre_seasonal = 70
seasonal_min_weeks = 20           # exige más historia estacional (más robustez estadística)

# ============== Moderado ==============
volatility_percentile = 0.85
correlation_percentile = 0.75
max_assets_in_portfolio = 10
max_weight_per_asset = 0.22
min_weight_per_asset = 0.001

use_etf_constraint = True
etf_min_weight = 0.00
etf_max_weight = 0.20

use_delta_filter = True
delta_min = 0.45

use_iv_shrinkage = True
shrinkage_min = 0.02
shrinkage_max = 0.70
ratio_band = 0.25

n_top_international = 10
n_pre_seasonal = 60
seasonal_min_weeks = 15

# ============== Agresivo ==============
volatility_percentile = 0.97      # casi no filtra por volatilidad, deja pasar activos de alta vol
correlation_percentile = 0.90     # tolera alta correlación con SPY (apuestas de beta concentrado)
max_assets_in_portfolio = 6       # cartera concentrada
max_weight_per_asset = 0.35       # permite apuestas grandes por activo
min_weight_per_asset = 0.001

use_etf_constraint = True
etf_min_weight = 0.00
etf_max_weight = 0.05             # casi todo en stock-picking, mínimo ETF

use_delta_filter = True
delta_min = 0.30                  # deja pasar activos más especulativos/OTM-like

use_iv_shrinkage = True
shrinkage_min = 0.02
shrinkage_max = 0.40              # pesa fuerte hacia IV (reactiva al pricing actual del mercado)
ratio_band = 0.20

n_top_international = 15          # más exposición a mercados emergentes/menos líquidos
n_pre_seasonal = 45
seasonal_min_weeks = 10           # tolera menos historia, prioriza señal reciente

# Minimum Variance (No Horizon)

# ============== Conservador ==============
volatility_percentile = 0.55      # solo el tercio menos volátil del universo
correlation_percentile = 0.60     # prioriza activos poco correlacionados con SPY (diversificación real)
max_assets_in_portfolio = 15      # más nombres, menor concentración por activo
max_weight_per_asset = 0.12       # techo bajo, evita concentración
min_weight_per_asset = 0.001

use_etf_constraint = True
etf_min_weight = 0.30             # base sólida en ETFs diversificados
etf_max_weight = 0.55

use_delta_filter = True
delta_min = 0.55                  # exige mayor probabilidad de éxito direccional

use_iv_shrinkage = True
shrinkage_min = 0.35
shrinkage_max = 0.85              # pesa fuerte hacia vol histórica (más estable)
ratio_band = 0.30

n_top_international = 5           # menor exposición a mercados menos líquidos
n_pre_seasonal = 70
seasonal_min_weeks = 20           # exige más historia estacional (más robustez estadística)

# ============== Moderado ==============
volatility_percentile = 0.85
correlation_percentile = 0.75
max_assets_in_portfolio = 10
max_weight_per_asset = 0.22
min_weight_per_asset = 0.001

use_etf_constraint = True
etf_min_weight = 0.00
etf_max_weight = 0.20

use_delta_filter = True
delta_min = 0.45

use_iv_shrinkage = True
shrinkage_min = 0.02
shrinkage_max = 0.70
ratio_band = 0.25

n_top_international = 10
n_pre_seasonal = 60
seasonal_min_weeks = 15

# ============== Agresivo ==============
volatility_percentile = 0.97      # casi no filtra por volatilidad, deja pasar activos de alta vol
correlation_percentile = 0.90     # tolera alta correlación con SPY (apuestas de beta concentrado)
max_assets_in_portfolio = 6       # cartera concentrada
max_weight_per_asset = 0.35       # permite apuestas grandes por activo
min_weight_per_asset = 0.001

use_etf_constraint = True
etf_min_weight = 0.00
etf_max_weight = 0.05             # casi todo en stock-picking, mínimo ETF

use_delta_filter = True
delta_min = 0.30                  # deja pasar activos más especulativos/OTM-like

use_iv_shrinkage = True
shrinkage_min = 0.02
shrinkage_max = 0.40              # pesa fuerte hacia IV (reactiva al pricing actual del mercado)
ratio_band = 0.20

n_top_international = 15          # más exposición a mercados emergentes/menos líquidos
n_pre_seasonal = 45
seasonal_min_weeks = 10           # tolera menos historia, prioriza señal reciente


# Quadratic Utility Profiles

# ============== Conservador ==============
lambda_ = 6.0                     # alta aversión al riesgo (según guía del propio script)
max_weight = 0.12

weight_sharpe = 0.30
weight_low_vol = 0.50             # prioriza baja volatilidad sobre Sharpe puro
weight_decorr = 0.20

volatility_percentile = 0.45      # solo el segmento menos volátil
correlation_percentile = 0.50     # exige mayor descorrelación con el pool

n_pre_seasonal = 80               # pool más amplio = más margen para diversificar
n_divers_candidates = 50

use_delta_filter = True
delta_min = 0.55

pct_etf_deseado = 0.55            # base sólida en ETFs
pct_etf_tolerancia = 0.10

max_region_weight = 0.35          # limita concentración geográfica

seasonal_vol_ratio_max = 1.15     # estricto con activos de temporada mala
skew_z_threshold = 1.0            # descarta más agresivamente skew anómalo
iv_outlier_multiplier = 3.0       # más desconfianza de IV inflada

# ============== Moderado ==============
lambda_ = 2.5
max_weight = 0.18

weight_sharpe = 0.40
weight_low_vol = 0.35
weight_decorr = 0.25

volatility_percentile = 0.60
correlation_percentile = 0.65

n_pre_seasonal = 60
n_divers_candidates = 40

use_delta_filter = True
delta_min = 0.45

pct_etf_deseado = 0.40
pct_etf_tolerancia = 0.05

max_region_weight = 0.60

seasonal_vol_ratio_max = 1.35
skew_z_threshold = 1.5
iv_outlier_multiplier = 4.0

# ============== Agresivo ==============
lambda_ = 0.8                     # baja aversión al riesgo (según guía del propio script)
max_weight = 0.30

weight_sharpe = 0.55              # prioriza Sharpe/retorno sobre baja vol
weight_low_vol = 0.15
weight_decorr = 0.30

volatility_percentile = 0.85      # deja pasar activos de alta vol
correlation_percentile = 0.85     # tolera mayor correlación (apuestas de beta)

n_pre_seasonal = 45               # pool más concentrado
n_divers_candidates = 30

use_delta_filter = True
delta_min = 0.30                  # filtro de convicción más laxo

pct_etf_deseado = 0.10            # casi todo stock-picking
pct_etf_tolerancia = 0.10

max_region_weight = 0.80          # permite mayor concentración geográfica

seasonal_vol_ratio_max = 1.80     # tolera más spikes de vol estacional
skew_z_threshold = 2.0            # más permisivo, conserva nombres especulativos
iv_outlier_multiplier = 6.0       # más reactivo al pricing actual del mercado


# Quadratic Utility Profiles (No Horizon)

# ============ CONSERVADOR ============
lambda_ = 6.0
max_weight = 0.12

weight_sharpe = 0.30
weight_low_vol = 0.50
weight_decorr = 0.20

volatility_percentile = 0.45
correlation_percentile = 0.50

n_pre_filter = 80
n_filter_candidates = 50

recent_vol_window_min_weeks = 20     # ventana más larga = estimado más estable
recent_vol_window_max_weeks = 26
recent_vol_ratio_max = 1.15          # estricto con spikes de vol reciente
recent_vol_min_survivors = 22

options_dte_cap_days = 90

iv_vs_realized_ratio_max = 1.15      # descarta activos con flujo de opciones "caliente"
iv_min_survivors = 16

use_delta_filter = True
delta_min = 0.55

pct_etf_deseado = 0.55
pct_etf_tolerancia = 0.10

max_region_weight = 0.35
skew_z_threshold = 1.0
iv_outlier_multiplier = 3.0

# ============ MODERADO ============
lambda_ = 2.5
max_weight = 0.18

weight_sharpe = 0.40
weight_low_vol = 0.35
weight_decorr = 0.25

volatility_percentile = 0.65
correlation_percentile = 0.65

n_pre_filter = 65
n_filter_candidates = 42

recent_vol_window_min_weeks = 15
recent_vol_window_max_weeks = 24
recent_vol_ratio_max = 1.35
recent_vol_min_survivors = 18

options_dte_cap_days = 90

iv_vs_realized_ratio_max = 1.35
iv_min_survivors = 14

use_delta_filter = True
delta_min = 0.42

pct_etf_deseado = 0.30
pct_etf_tolerancia = 0.08

max_region_weight = 0.55
skew_z_threshold = 1.5
iv_outlier_multiplier = 4.0

# ============ AGRESIVO ============
lambda_ = 0.5
max_weight = 0.30

weight_sharpe = 0.55
weight_low_vol = 0.15
weight_decorr = 0.30

volatility_percentile = 0.85
correlation_percentile = 0.85

n_pre_filter = 45
n_filter_candidates = 30

recent_vol_window_min_weeks = 13     # ventana corta = más reactiva a lo reciente
recent_vol_window_max_weeks = 18
recent_vol_ratio_max = 1.80
recent_vol_min_survivors = 14

options_dte_cap_days = 90

iv_vs_realized_ratio_max = 1.80      # tolera/acepta flujo especulativo
iv_min_survivors = 10

use_delta_filter = True
delta_min = 0.30

pct_etf_deseado = 0.10
pct_etf_tolerancia = 0.10

max_region_weight = 0.80
skew_z_threshold = 2.0
iv_outlier_multiplier = 6.0